Repository alibaba-fusion/next, pull requests merged in 2019-11, with the labels that each got.

#1326 Feat divider
  .eslintignore
  .fusion
  .prettierignore
  docs/avatar/adaptor/index.jsx
  docs/avatar/demo/basic.md
  docs/avatar/demo/type.md
  docs/avatar/demo/with-badge.md
  docs/avatar/index.en-us.md
  docs/avatar/index.md
  docs/avatar/theme/index.jsx
  docs/divider/adaptor/index.jsx
  docs/divider/demo/basic.md
  docs/divider/demo/orientation.md
  docs/divider/index.en-us.md
  docs/divider/index.md
  docs/divider/theme/index.jsx
  docs/icon/index.md
  package.json
  scripts/config.js
  scripts/create-new.js
  scripts/create/docs/adaptor/index.jsx
  scripts/create/docs/demo/basic.md
  scripts/create/docs/index.en-us.md
  scripts/create/docs/index.md
  scripts/create/docs/theme/index.jsx
  scripts/create/src/index.jsx
  scripts/create/src/main.scss
  scripts/create/src/scss/mixin.scss
  scripts/create/src/scss/variable.scss
  scripts/create/src/style.js
  scripts/create/test/a11y-spec.js
  scripts/create/test/index-spec.js
  scripts/create/types/index.d.ts
  scripts/server/middlewares/rebuild-scss.js
  scripts/server/tpls/config.ejs
  src/avatar/index.jsx
  src/avatar/main.scss
  src/avatar/scss/mixin.scss
  src/avatar/scss/variable.scss
  src/avatar/style.js
  src/divider/index.jsx
  src/divider/main.scss
  src/divider/scss/mixin.scss
  src/divider/scss/variable.scss
  src/divider/style.js
  src/icon/index.jsx
  src/index.js
  test/avatar/a11y-spec.js
  test/avatar/index-spec.js
  test/divider/a11y-spec.js
  test/divider/index-spec.js
  types/avatar/index.d.ts
  types/divider/index.d.ts
  types/icon/index.d.ts
  types/index.d.ts
Labels: PR: review-approved

#1362 chore(Input): <div> in <p> cause warning
  src/input/input.jsx
  src/input/textarea.jsx
  src/rating/rating.jsx
Labels: PR: unreviewd

#1355 feat(Range): add preview mode
  docs/form/demo/preview.md
  src/range/view/range.jsx
  test/range/index-spec.js
Labels: PR: review-changes-request

#1352 feat(Radio): add preview mode
  docs/form/demo/preview.md
  src/radio/radio-group.jsx
  src/radio/radio.jsx
  test/radio/group-spec.js
  test/radio/index-spec.js
Labels: PR: review-changes-request

#1351 feat(Checkbox): add preview mode
  docs/form/demo/preview.md
  src/checkbox/checkbox-group.jsx
  src/checkbox/checkbox.jsx
  test/checkbox/group-spec.js
  test/checkbox/index-spec.js
Labels: PR: review-changes-request

#1354 feat(Switch): add preview mode
  src/locale/en-us.js
  src/locale/ja-jp.js
  src/locale/zh-cn.js
  src/locale/zh-tw.js
  src/switch/index.jsx
  test/switch/index-spec.js
  types/locale/default.d.ts
Labels: PR: review-changes-request

#1368 Feat Support Preview Mode
  src/cascader-select/cascader-select.jsx
  src/date-picker/date-picker.jsx
  src/date-picker/month-picker.jsx
  src/date-picker/range-picker.jsx
  src/date-picker/year-picker.jsx
  src/time-picker/time-picker.jsx
  src/tree-select/tree-select.jsx
  test/cascader-select/index-spec.js
  test/date-picker/index-spec.js
  test/time-picker/index-spec.js
  test/tree-select/index-spec.js
Labels: PR: review-approved

#1366 NumberPicker & Input
  docs/input/theme/index.jsx
  docs/number-picker/demo/size.md
  src/form/item.jsx
  src/form/main.scss
  src/form/scss/variable.scss
  src/input/base.jsx
  src/input/input.jsx
  src/input/main.scss
  src/input/scss/variable.scss
  src/number-picker/main.scss
  src/number-picker/number-picker.jsx
  src/number-picker/scss/variable.scss
Labels: PR: review-approved

#1284 Feat date picker
  docs/date-picker/demo/basic.md
  docs/date-picker/demo/default.md
  docs/date-picker/index.en-us.md
  docs/date-picker/index.md
  src/calendar/index.jsx
  src/calendar/scss/table.scss
  src/date-picker/index.jsx
  src/date-picker/main.scss
  src/date-picker/range-picker.jsx
  src/date-picker/scss/date-picker.scss
  src/date-picker/scss/variable.scss
  src/date-picker/util/index.js
  src/date-picker/week-picker.jsx
  src/locale/en-us.js
  src/locale/ja-jp.js
  src/locale/zh-cn.js
  src/locale/zh-tw.js
  test/date-picker/index-spec.js
  types/date-picker/index.d.ts
  types/locale/default.d.ts
Labels: PR: review-approved

#1276 feat(Timeline): update lifecycle
  docs/timeline/demo/fold.md
  src/cascader/cascader.jsx
  src/timeline/view/timeline.jsx
  test/timeline/index-spec.js
Labels: PR: review-changes-request, PR: unreviewed

#1247 feat(Table): add colSpan to merge cell of theader, close #993
  docs/table/demo/colspan.md
  docs/table/demo/selection.md
  docs/table/index.en-us.md
  docs/table/index.md
  src/table/base/header.jsx
  src/table/base/row.jsx
  src/table/column.jsx
  src/table/selection.jsx
  test/table/index-spec.js
  types/table/index.d.ts
Labels: PR: unreviewed

#1236 fix(Radio): support config disabled & checked background/color/icon
  src/radio/main.scss
  src/radio/scss/variable.scss
Labels: PR: review-approved
