Repository alibaba-fusion/next, pull requests merged in 2020-03, with the labels that each got.

#1637 Feat(Checkbox): make checkbox icon configurable
  src/checkbox/checkbox.jsx
  src/checkbox/main.scss
  src/checkbox/scss/variable.scss
Labels: PR: review-changes-request

#1631 feat(Tab): make tab icon configurable
  docs/date-picker/index.md
  docs/form/index.md
  docs/menu/index.md
  docs/number-picker/index.md
  docs/search/index.md
  docs/tab/index.en-us.md
  docs/tab/index.md
  src/tab/main.scss
  src/tab/scss/variable.scss
  src/tab/tab.jsx
  src/tab/tabs/nav.jsx
  types/tab/index.d.ts
Labels: PR: review-changes-request

#1634 feat(Calendar): add icons
  src/calendar/head/date-panel-header.jsx
  src/calendar/head/month-panel-header.jsx
  src/calendar/head/range-panel-header.jsx
  src/calendar/head/year-panel-header.jsx
  src/calendar/main.scss
  src/calendar/scss/variable.scss
Labels: PR: review-changes-request

#1574 feat(Icon): add icons
  .fusion
  docs/icon/demo/type.md
  src/core/style/_icon.scss
  src/icon/main.scss
Labels: PR: unreviewed

#1648 feat(Select): make icons configurable
  docs/select/theme/index.jsx
  src/select/main.scss
  src/select/scss/variable.scss
  src/select/select.jsx
Labels: PR: unreviewed

#1617 fix(Overlay& Nav): wrong position when pinElement is fixed
  docs/nav/demo/custom.md
  docs/nav/demo/fixed.md
  src/menu/view/popup-item.jsx
  src/nav/sub-nav.jsx
  src/overlay/overlay.jsx
  src/overlay/position.jsx
  src/overlay/utils/position.js
  test/nav/a11y-spec.js
  test/nav/index-spec.js
Labels: PR: unreviewed

#1646 feat(Field): add api getValueFormatter/setValueFormatter fix #781
  docs/field/demo/normalize.md
  docs/field/index.en-us.md
  docs/field/index.md
  package.json
  test/field/index-spec.js
Labels: PR: review-changes-request

#1659 feat(Step): adjust while receive props
  docs/step/demo/controlled.md
  src/step/scss/dot.scss
  src/step/view/step-item.jsx
  src/step/view/step.jsx
Labels: PR: review-approved

#1624 feat(Button): add icons for custom loading icon
  docs/button/demo/accessibility.md
  docs/button/demo/component.md
  docs/button/demo/custom-icons.md
  docs/button/demo/disabled.md
  docs/button/demo/ghost.md
  docs/button/demo/group.md
  docs/button/demo/loading.md
  docs/button/index.en-us.md
  docs/button/index.md
  src/button/main.scss
  src/button/scss/mixin.scss
  src/button/view/button.jsx
  test/button/index-spec.js
  types/button/index.d.ts
Labels: PR: review-changes-request

#1681 fix(Balloon): add break-word to Tooltip, close #1680
  docs/balloon/index.en-us.md
  docs/balloon/index.md
  src/balloon/main.scss
  src/balloon/tooltip.jsx
Labels: PR: review-approved, PR: unreviewed

#1686 fix(Tree): stop dragover event propagation, close #1662
  src/tree/view/tree-node.jsx
  test/tree/index-spec.js
Labels: PR: unreviewed

#1677 fix(Tab): wait until animation end, close #1674
  src/tab/tabs/nav.jsx
  test/tab/index-spec.js
Labels: PR: review-changes-request

#1713 fix(CascaderSelect): resolve resultAutoWidth prop unuseless, close #1710
  src/cascader-select/cascader-select.jsx
  test/cascader-select/index-spec.js
Labels: PR: review-approved

#1708 fix(TreeSelect): resolve repeated label issue, close #1633
  docs/tree/demo/control-check.md
  src/tree/view/tree.jsx
  src/tree/view/util.js
  test/tree/index-spec.js
Labels: PR: unreviewed
