Repository alibaba-fusion/next, pull requests merged in 2021-11, with the labels that each got.

#3481 Fix input padding, add api hoverShowClear
  docs/input/demo/clear.md
  docs/input/demo/inner.md
  docs/input/index.en-us.md
  docs/input/index.md
  src/input/input.jsx
  src/input/main.scss
  src/input/scss/mixin.scss
  types/input/index.d.ts
Labels: PR: review-required

#3424 feat(TreeSelect): support preserveNonExistentValue props
  docs/tree-select/demo/non-existent-value.md
  docs/tree-select/index.en-us.md
  docs/tree-select/index.md
  package.json
  src/tree-select/tree-select.jsx
  test/tree-select/index-spec.js
  types/tree-select/index.d.ts
Labels: 💡 Feature Request, PR: review-required, PR: review-changes-request

#3519 fix(overlay): compatible with react17, fix #2959
  docs/overlay/index.en-us.md
  docs/overlay/index.md
  src/overlay/overlay.jsx
  test/overlay/index-spec.js
  types/overlay/index.d.ts
Labels: PR: review-required

#3525 feat(DatePicker2): move Popup panel when RangePicker focus change, close #3492
  src/date-picker2/picker.jsx
Labels: PR: review-required

#3445 Feat(TreeSelect): use tagInline to support single line display, close #3360
  docs/tree-select/demo/inline.md
  docs/tree-select/index.en-us.md
  docs/tree-select/index.md
  src/locale/en-us.js
  src/locale/id-id.js
  src/locale/it-it.js
  src/locale/ja-jp.js
  src/locale/ko-kr.js
  src/locale/ms-my.js
  src/locale/pt-pt.js
  src/locale/th-th.js
  src/locale/vi-vn.js
  src/locale/zh-cn.js
  src/locale/zh-hk.js
  src/locale/zh-tw.js
  src/rating/rating.jsx
  src/tree-select/tree-select.jsx
  src/util/object.js
  test/tree-select/index-spec.js
  types/tree-select/index.d.ts
Labels: 💡 Feature Request, PR: review-required

#3524 Feat(tree): support custom item render, close #3430
  docs/tree/index.en-us.md
  docs/tree/index.md
  src/tree/view/tree.jsx
  test/tree/index-spec.js
  types/tree/index.d.ts
Labels: PR: review-required

#3535 fix(Form): ts formItem and formProps add name, close #3512
  types/form/index.d.ts
Labels: PR welcome, Typescript

#3537 fix(Affix): suport resize container width fix #3536
  src/affix/index.jsx
Labels: PR: review-required

#3556 docs(Dialog): update readme
  docs/dialog/demo/height.md
  docs/dialog/demo/quick.md
  docs/dialog/index.en-us.md
  docs/dialog/index.md
  src/balloon/tooltip.jsx
  src/dialog/dialog.jsx
  src/dialog/inner.jsx
  types/dialog/index.d.ts
Labels: PR: review-required

#3554 fix(NumberPicker): isPreview add innerAfter, close #3553
  src/number-picker/number-picker.jsx
Labels: PR welcome

#3558 fix(Dialog): shake while dialog hiding after scrollbar show
  docs/dialog/index.en-us.md
  docs/dialog/index.md
  src/dialog/dialog-v2.jsx
  src/dialog/dialog.jsx
  types/balloon/index.d.ts
  types/dialog/index.d.ts
Labels: PR: review-required

#3517 fix(Tab): should realtime update dropdown, close #3516
  src/tab/tabs/nav.jsx
  src/tab/tabs/utils.js
Labels: PR welcome, PR: review-required
