Repository alibaba-fusion/next, pull requests merged in 2021-06, with the labels that each got.

#3029 feat(NumberPicker): refactor interactive logic
  src/number-picker/number-picker.jsx
  test/number-picker/index-spec.js
Labels: PR: review-approved

#3051 fix(Form.Item): add fullWidth type
  types/form/index.d.ts
Labels: Typescript

#3055 fix(Overlay): should set overflow hidden to container
  src/overlay/overlay.jsx
  test/overlay/index-spec.js
Labels: PR: review-changes-request, PR: review-required

#3046 Feat/bignumber
  docs/number-picker/demo/bignumber.md
  package.json
  src/number-picker/number-picker.jsx
  test/number-picker/index-spec.js
Labels: PR: review-changes-request

#3065 docs(Form): update usage of trigger fix #3063
  docs/field/index.md
  docs/form/index.md
  src/form/item.jsx
Labels: PR: review-required

#3071 fix(Overlay): fix svg element position bug,close ##3070
  src/overlay/utils/position.js
  test/overlay/index-spec.js
Labels: PR: review-approved

#3076 fix(Form): error state in functional children of FormItem fix #3075
  src/form/item.jsx
  test/form/validate-spec.js
Labels: PR: review-approved

#3088 fix(DatePicker2): RangeDate check bug when set disabled, close #3086
  src/date-picker2/picker.jsx
  test/date-picker2/index-spec.js
Labels: PR: review-required

#3083 Slider issues
  src/shell/main.scss
  src/slider/slick/inner-slider.jsx
  src/slider/slick/mixins/helpers.js
  test/slider/issue-spec.js
Labels: PR: review-required

#3089 chore(*): update ts file
  types/calendar2/index.d.ts
  types/date-picker2/index.d.ts
  types/time-picker2/index.d.ts
  types/tree-select/index.d.ts
Labels: PR: review-required

#3101 fix(Select): item can selected in popupAutoFocus fix #3038
  src/select/base.jsx
Labels: PR: review-required

#3112 fix(Breadcurmb): fix height to 16px in case of $s-base=3 fix #3111
  src/breadcrumb/scss/variable.scss
Labels: PR: review-required

#3114 fix(Overlay): overflow bug with mulitple overlay, close#3104
  src/overlay/overlay.jsx
  test/overlay/index-spec.js
Labels: PR: review-required

#3138 fix(Overlay): should ignore hidden container
  src/overlay/overlay.jsx
  test/overlay/index-spec.js
Labels: PR: review-required
